#!/usr/bin/env python3
"""Generate a driver .c that lists every `ATF_TC_BODY(name, tc)`
declaration in the input test source.

Output:
    extern void atf_tc_body_foo(void *);
    extern void atf_tc_body_bar(void *);
    struct yos_atf_entry { const char *name; void (*fn)(void *); }
        yos_atf_table[] = {
        {"foo", atf_tc_body_foo},
        {"bar", atf_tc_body_bar},
        {NULL, NULL}
    };

Linked into the test binary together with the test source + run.c.
"""
from __future__ import annotations
import re
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 3:
        print(f'usage: {sys.argv[0]} <test.c> <out.c>', file=sys.stderr)
        return 2
    src = Path(sys.argv[1]).read_text(encoding='utf-8')
    out = Path(sys.argv[2])

    names = re.findall(r'\bATF_TC_BODY\s*\(\s*(\w+)\s*,', src)
    seen = set()
    deduped = []
    for n in names:
        if n in seen:
            continue
        seen.add(n)
        deduped.append(n)

    lines = ['/* generated by gen_driver.py */']
    for n in deduped:
        lines.append(f'extern void atf_tc_body_{n}(void *);')
    lines.append('struct yos_atf_entry { const char *name; void (*fn)(void *); };')
    lines.append('struct yos_atf_entry yos_atf_table[] = {')
    for n in deduped:
        lines.append(f'    {{ "{n}", atf_tc_body_{n} }},')
    lines.append('    { (void *)0, (void *)0 }')
    lines.append('};')
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'[gen_driver] {len(deduped)} test(s) in {Path(sys.argv[1]).name}',
          file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
