#!/usr/bin/env python3
"""Emit a mimalloc unity TU. Same trick as build-tools/wasm3/.

mimalloc upstream actually ships a `static.c` that already #include's
the rest of its sources — we just point the unity at that. Keeps us
shielded from upstream file-list changes."""
from __future__ import annotations
import argparse, sys
from pathlib import Path


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument('--source-dir', required=True, type=Path)
    p.add_argument('--output',     required=True, type=Path)
    args = p.parse_args()
    src = args.source_dir.resolve()
    args.output.write_text(
        '/* AUTO-GENERATED by emit_unity.py */\n'
        f'#include "{(src / "static.c").as_posix()}"\n'
    )
    print(f'[mimalloc] emitted unity {args.output}', file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
