#!/usr/bin/env bash
# setup.sh — configure the yos host build for arm64 Apple TV (real device).
#
#   ./build-tools/tvos/setup.sh
#
# Produces build-tvos-arm64/, an out-of-tree meson build that
# cross-compiles libyos.a against the AppleTVOS SDK. The deploy.sh
# script then bolts that lib into a signed .app bundle and installs
# it to a paired Apple TV via `xcrun devicectl`.
#
# Optional deps disabled at meson time (no AppleTVOS SDK packages
# for these):
#   - msgpack-c     → -Dwith_yctl=disabled
#   - libpython3.12 → -Dwith_libpython=disabled
#
# Builds yos as a STATIC LIBRARY, not an executable: tvOS apps must
# enter through UIApplicationMain in the bundle's main(), which
# launcher.m supplies. See -Dbuild_static_lib=true.

set -euo pipefail

cd "$(dirname "$0")/../.."
REPO="$PWD"

SDK="$(xcrun --sdk appletvos --show-sdk-path)"
CLANG="$(xcrun --sdk appletvos --find clang)"
TOOLCHAIN_BIN="$(dirname "$CLANG")"
TOOLCHAIN_AR="$TOOLCHAIN_BIN/ar"
TOOLCHAIN_STRIP="$TOOLCHAIN_BIN/strip"
TOOLCHAIN_RANLIB="$TOOLCHAIN_BIN/ranlib"

# build-tools/sysroot/skel.sh needs a clang with the wasm32 backend
# to compile the empty stub libs + crt1. Apple's /usr/bin/clang on
# darwin has no wasm32 target. If the caller is in `nix develop`,
# $YOS_WASM_CLANG is already set; otherwise probe nixpkgs's clang
# binaries in the store and pick the first that accepts -target
# wasm32-unknown-unknown.
if [ -z "${YOS_WASM_CLANG:-}" ]; then
    for c in $(find /nix/store -maxdepth 4 -name clang -type f 2>/dev/null); do
        if echo 'int main(){return 0;}' \
           | "$c" -target wasm32-unknown-unknown -nostdlib -x c - -c -o /tmp/.yos_wasm_probe.o 2>/dev/null; then
            export YOS_WASM_CLANG="$c"
            rm -f /tmp/.yos_wasm_probe.o
            break
        fi
    done
    if [ -z "${YOS_WASM_CLANG:-}" ]; then
        echo "[tvos] no wasm32-capable clang found. Either:" >&2
        echo "        - run from inside \`nix develop\`, or" >&2
        echo "        - set YOS_WASM_CLANG=/path/to/clang yourself." >&2
        exit 1
    fi
fi
echo "[tvos] wasm clang : $YOS_WASM_CLANG"

BUILD_DIR="$REPO/build-tvos-arm64"
CROSS_TMPL="$REPO/build-tools/tvos/cross-arm64-tvos.txt"
CROSS_OUT="$REPO/build-tools/tvos/cross-arm64-tvos.generated.txt"

sed \
    -e "s|@SDK@|$SDK|g" \
    -e "s|@CLANG@|$CLANG|g" \
    -e "s|@TOOLCHAIN_AR@|$TOOLCHAIN_AR|g" \
    -e "s|@TOOLCHAIN_STRIP@|$TOOLCHAIN_STRIP|g" \
    -e "s|@TOOLCHAIN_RANLIB@|$TOOLCHAIN_RANLIB|g" \
    "$CROSS_TMPL" > "$CROSS_OUT"

echo "[tvos] SDK   : $SDK"
echo "[tvos] clang : $CLANG"
echo "[tvos] cross : $CROSS_OUT"
echo "[tvos] build : $BUILD_DIR"

MESON_FLAGS=(
    --cross-file "$CROSS_OUT"
    -Dwith_yctl=disabled
    -Dwith_libpython=disabled
    -Dbuild_static_lib=true
    -Dtvos_unblock=true
)

if [ -d "$BUILD_DIR" ]; then
    meson setup --reconfigure "${MESON_FLAGS[@]}" "$BUILD_DIR"
else
    meson setup "${MESON_FLAGS[@]}" "$BUILD_DIR"
fi

# Persist YOS_WASM_CLANG so `meson compile` invoked from a fresh shell
# (or from deploy.sh) sees the same path skel.sh needs. deploy.sh
# sources this file. Idempotent: rewritten on every setup.sh run.
cat > "$BUILD_DIR/.yos_env" <<EOF
# Auto-generated by build-tools/tvos/setup.sh. Source this to inherit
# the wasm-capable clang path that skel.sh needs at compile time.
export YOS_WASM_CLANG="$YOS_WASM_CLANG"
EOF

echo
echo "[tvos] setup ok. Compile with:"
echo "    source $BUILD_DIR/.yos_env"
echo "    meson compile -C $BUILD_DIR yos"
echo
echo "[tvos] or end-to-end via:"
echo "    ./build-tools/tvos/deploy.sh"
