#!/usr/bin/env bash
# libevent — event loop library (tmux's hard dependency). autoconf
# cross-build to wasm32. We keep only the select(2)/poll(2) backends
# (yos bridges those) and disable every kernel-specific notifier
# (epoll/kqueue/devpoll/evport/eventfd/signalfd) plus threads, openssl,
# benchmarks and the regression suite.
set -euo pipefail

NAME=libevent
VERSION=2.1.12-stable
URL="https://github.com/libevent/libevent/releases/download/release-${VERSION}/libevent-${VERSION}.tar.gz"
SHA256="92e6de1be9ec176428fd2367677e61ceffc2ee1cb119035037a27d346b0403bb"
DEPS=""

: "${ROOT:?}"; : "${PREFIX:?}"; : "${WASM_CC:?}"; : "${WASM_SYSROOT:?}"
: "${WORK:=$ROOT/build-linux/wasm-pkgs/${NAME}-${VERSION}}"

mkdir -p "$WORK" "$PREFIX/lib" "$PREFIX/include"

TARBALL="$WORK/${NAME}-${VERSION}.tar.gz"
[[ -f "$TARBALL" ]] || curl -fsSL "$URL" -o "$TARBALL"
echo "${SHA256}  $TARBALL" | sha256sum -c - > /dev/null

SRC="$WORK/src"
if [[ ! -f "$SRC/.extracted" ]]; then
    rm -rf "$SRC"; mkdir -p "$SRC"
    tar -xzf "$TARBALL" -C "$SRC" --strip-components=1
    # config.sub predates wasm32 — short-circuit the triple. It can live
    # at the top level OR under build-aux/; patch every copy.
    while IFS= read -r CS; do
        python3 - "$CS" <<'PY'
import sys, pathlib
p = pathlib.Path(sys.argv[1]); t = p.read_text()
nl = t.find('\n') + 1
shim = 'case ${1:-} in\n    wasm32-*|wasm64-*) echo "$1"; exit 0 ;;\nesac\n'
p.write_text(t[:nl] + shim + t[nl:]); print("config.sub patched:", sys.argv[1])
PY
    done < <(find "$SRC" -name config.sub)
    touch "$SRC/.extracted"
fi

# Build in-tree: libevent generates event2/event-config.h into the tree
# and its compile rules expect it on the in-tree include path.
BLD="$SRC"; cd "$BLD"
make distclean 2>/dev/null || true

CFLAGS_W="$WASM_CFLAGS -D_GNU_SOURCE -D__FreeBSD__=14"
# Building a static archive — NO crt1.o (that's for the final executable;
# libtool rejects it as a "non-libtool object" when making a library).
LDFLAGS_W="-target wasm32-unknown-unknown -nostdlib $WASM_LDFLAGS \
    -L$WASM_SYSROOT/usr/lib"

# Cross-compile cache: backends that probe the kernel must be answered
# "no" so configure doesn't link a test against epoll_create/kqueue etc.
CACHE="$BLD/config.cache"
cat > "$CACHE" <<'CACHE_EOF'
ac_cv_func_epoll_create=no
ac_cv_func_epoll_ctl=no
ac_cv_func_kqueue=no
ac_cv_func_port_create=no
ac_cv_func_eventfd=no
ac_cv_func_signalfd=no
ac_cv_func_pipe2=no
ac_cv_func_accept4=no
ac_cv_func_arc4random=yes
ac_cv_func_arc4random_buf=yes
ac_cv_func_arc4random_addrandom=no
ac_cv_func_getrandom=no
ac_cv_func_getentropy=no
ac_cv_func_sysctl=yes
ac_cv_func_clock_gettime=yes
ac_cv_func_mmap=no
ac_cv_func_select=yes
ac_cv_func_poll=yes
ac_cv_header_sys_epoll_h=no
ac_cv_header_sys_event_h=no
ac_cv_header_sys_eventfd_h=no
ac_cv_header_sys_signalfd_h=no
ac_cv_header_port_h=no
CACHE_EOF

CC="$WASM_CC" CFLAGS="$CFLAGS_W" CPPFLAGS="$CFLAGS_W" LDFLAGS="$LDFLAGS_W" \
LIBS="-lc -lyos_stubs" CPP="$WASM_CC -E $CFLAGS_W" \
"$SRC/configure" \
    --host=wasm32-unknown-unknown \
    --prefix="$PREFIX" \
    --cache-file="$CACHE" \
    --disable-shared --enable-static \
    --disable-openssl --disable-mbedtls \
    --disable-thread-support \
    --disable-debug-mode --disable-malloc-replacement \
    --disable-libevent-regress --disable-samples \
    || { echo "[$NAME] configure failed; tail config.log:"; tail -60 "$BLD/config.log"; exit 1; }

# Generate the config header FIRST — under `make -j` it races the .c
# compiles and they fail with "event2/event-config.h not found".
make include/event2/event-config.h 2>/dev/null || true
ls -la include/event2/event-config.h 2>/dev/null || echo "WARN: event-config.h not generated by make rule"
make -j"$(nproc 2>/dev/null || echo 4)" libevent.la libevent_core.la libevent_extra.la \
    || make \
    || { echo "[$NAME] make failed"; exit 1; }

# Install headers + the static archives.
make install-data 2>/dev/null || cp -r "$SRC/include/"* "$PREFIX/include/" 2>/dev/null || true
mkdir -p "$PREFIX/include/event2"
cp -r include/event2/*.h "$PREFIX/include/event2/" 2>/dev/null || true
cp -r "$SRC/include/event2/"*.h "$PREFIX/include/event2/" 2>/dev/null || true
cp "$SRC/include/"*.h "$PREFIX/include/" 2>/dev/null || true
find . -name 'libevent*.a' -exec cp {} "$PREFIX/lib/" \;
# .libs holds the real archives for libtool builds.
find . -path '*/.libs/libevent*.a' -exec cp {} "$PREFIX/lib/" \; 2>/dev/null || true

cat > "$PREFIX/manifest.txt" <<EOF
name=libevent
version=${VERSION}
prefix=${PREFIX}
src=${SRC}
EOF
echo "[$NAME] installed → $PREFIX/lib/libevent.a"
