#!/usr/bin/env python3
"""Code generation from analyse-report.yaml.

This first pass focuses on the **constants_remap** table because it's
the highest-value, lowest-complexity slice of the analysis: scalars
whose names match across guest and host but whose integer values
differ (errno = 35 vs 11, CLOCK_MONOTONIC = 4 vs 1, …). The runtime
needs lookup functions to translate these at the boundary.

Outputs (under <build>/build-tools/api-generate/):

  yos_remap.h          public API: int yos_remap_<group>_g2h(int)
  yos_remap.c          switch-based implementations, one per group
  yos_remap_stats.txt  summary (counts per group)
  hooks_todo.yaml      skeleton listing every needs_policy function;
                       humans curate this by adding a chosen
                       translator strategy per entry.

Bridge wrappers for compatible/mechanical FUNCTIONS are NOT emitted
here yet — that's the next iteration. The remap tables and the
hooks_todo skeleton are what we wanted out of THIS pipeline stage:
* concrete code yos's host runtime can link against today
* a structured worklist of judgement calls humans need to make.

Constants are grouped by name-prefix because that mirrors how libc
exposes them — every errno is `E*`, every clock is `CLOCK_*`, every
open-flag is `O_*`. Anything that doesn't match a known prefix lands
in the `misc` group so we don't lose data; the runtime can ignore it
or someone can promote it to a real group later.
"""
from __future__ import annotations

import argparse
import sys
import textwrap
from collections import defaultdict
from pathlib import Path

import yaml


# Order matters — first match wins. Tighten before generic.
PREFIX_GROUPS: list[tuple[str, str]] = [
    # (group_name, prefix)
    ('errno',     'E'),         # EAGAIN, EINVAL, …
    ('signal',    'SIG'),       # SIGINT, SIGTERM, … (overrides E* via order)
    ('clockid',   'CLOCK_'),    # CLOCK_REALTIME, …
    ('openflag',  'O_'),        # O_RDONLY, O_NONBLOCK, …
    ('mmapflag',  'MAP_'),      # MAP_PRIVATE, …
    ('mprotflag', 'PROT_'),     # PROT_READ, …
    ('atflag',    'AT_'),       # AT_SYMLINK_NOFOLLOW, …
    ('sock',      'SOCK_'),     # SOCK_STREAM, …
    ('af',        'AF_'),       # AF_INET, …
    ('pf',        'PF_'),       # PF_INET, …
    ('msg',       'MSG_'),      # MSG_PEEK, …
    ('fcntl',     'F_'),        # F_DUPFD, F_GETFL, …
    ('shut',      'SHUT_'),     # SHUT_RD, SHUT_WR, SHUT_RDWR
    ('rlim',      'RLIMIT_'),   # RLIMIT_NOFILE, …
    ('s_i',       'S_I'),       # S_IRUSR, S_IFMT, … (mode bits)
    ('madv',      'MADV_'),     # MADV_NORMAL, …
    ('w',         'W'),         # WNOHANG, WIFEXITED, … (only if W*)
]


def _group_for(name: str) -> str:
    """Return the group label for a constant. Falls back to 'misc'.

    Some prefixes are sub-prefixes of others (`SIG` starts with `S` but
    we want it in 'signal' not 's_i'). Order in PREFIX_GROUPS handles
    that — `SIG` comes before `S_I`.
    """
    for group, prefix in PREFIX_GROUPS:
        if name.startswith(prefix):
            # Special-case: "W" is too greedy; only W* macros that
            # are actual wait-status helpers count.
            if group == 'w' and not (
                name.startswith('W') and (
                    name in ('WNOHANG', 'WUNTRACED', 'WCONTINUED', 'WEXITED',
                            'WSTOPPED', 'WNOWAIT', 'WIFEXITED', 'WEXITSTATUS',
                            'WIFSIGNALED', 'WTERMSIG', 'WIFSTOPPED', 'WSTOPSIG',
                            'WIFCONTINUED', 'WCOREDUMP'))):
                continue
            return group
    return 'misc'


def _split_groups(remap: dict) -> dict[str, list[tuple[str, int, int]]]:
    """Bucket remap entries by name-prefix group. Each entry: (name, guest_value, host_value).

    Always seeds every PREFIX_GROUPS bucket so the emitter produces a
    passthrough function even when the group ended up with zero entries
    on this host (e.g. on darwin all FreeBSD errno values already match
    so the errno bucket is empty — but yos source code still calls
    yos_remap_errno_h2g unconditionally and needs the symbol to link).
    """
    groups: dict[str, list] = defaultdict(list)
    for g, _ in PREFIX_GROUPS:
        groups.setdefault(g, [])
    for name, info in sorted(remap.items()):
        groups[_group_for(name)].append(
            (name, info.get('guest_value'), info.get('host_value'))
        )
    return groups


# ─── C emitters ──────────────────────────────────────────────────────

_HEADER_PROLOGUE = '''\
/*
 * Auto-generated by build-tools/api-generate/generate.py — DO NOT EDIT.
 *
 * Scalar value remaps between guest (FreeBSD-flavoured) and host libc.
 * Each pair of functions (`*_g2h`, `*_h2g`) translates one direction:
 *   _g2h: input from the guest, used when yos passes a constant down
 *         to the host (e.g. open(O_NONBLOCK)).
 *   _h2g: output to the guest, used when yos surfaces a host value
 *         back up (e.g. errno after read() returns -1).
 *
 * If the guest value isn't recognised the function returns the input
 * unchanged — caller must decide what that means in context.
 */
'''


def _emit_remap_function(name: str, pairs: list[tuple[str, int, int]],
                         direction: str) -> tuple[str, list[str]]:
    """direction='g2h' or 'h2g'.

    Returns (c_code, collision_notes). Collisions happen when the same
    SOURCE value is used by two different constants on one side
    (typical for flag bits reused across syscalls — Linux's
    AT_EACCESS and AT_REMOVEDIR are both 0x200, distinguished only by
    which syscall consumes them). C `switch` requires unique case
    labels, so we keep the first mapping and emit a comment for the
    others. The runtime caller has to know which syscall context it's
    in; a value-only remap can't disambiguate.
    """
    lines = [f'int yos_remap_{name}_{direction}(int v)', '{']
    notes: list[str] = []
    seen: dict[int, str] = {}
    if pairs:
        lines.append('    switch (v) {')
        for cname, gv, hv in pairs:
            src, dst = (gv, hv) if direction == 'g2h' else (hv, gv)
            if src is None or dst is None:
                continue
            if src in seen:
                first = seen[src]
                lines.append(f'    /* COLLISION: {cname} also has source value '
                             f'{src}; first claim {first} wins */')
                notes.append(f'{name}_{direction}: {cname} collides with {first} '
                             f'on source value {src}')
                continue
            seen[src] = cname
            lines.append(f'    case {src}: return {dst};   /* {cname} */')
        lines.append('    default:    return v;')
        lines.append('    }')
    else:
        lines.append('    return v;   /* empty group */')
    lines.append('}')
    return '\n'.join(lines), notes


def _emit_name_function(name: str, pairs: list[tuple[str, int, int]]) -> str:
    """Emit `const char *yos_name_<group>(int guest_v)` — symbolic name
    lookup, used by the strace-style bridge trace to render errno
    numbers, signal numbers, etc. as their constant names. Same data
    as the g2h/h2g switches; different orientation.

    Collision policy: when two constants share an integer value (e.g.
    FreeBSD's `EAI_AGAIN`=2 and `ENOENT`=2 — they live in different
    POSIX name domains but the prefix grouper threw both into 'errno'),
    we prefer the plain-prefix name over a known sub-prefix alias.
    Sub-prefix sets to deprioritise per group are listed in
    `_NAME_DEMOTE`. Unknown names sort alphabetically as before."""
    _NAME_DEMOTE = {
        'errno':  ('EAI_', 'EHOST', 'ERPC'),    # getaddrinfo & RPC aliases
        'signal': ('SIG_',),                     # SIG_DFL/SIG_IGN/SIG_ERR (action ptrs)
    }
    demote_prefixes = _NAME_DEMOTE.get(name, ())
    def _sort_key(p):
        cname = p[0]
        return (any(cname.startswith(pfx) for pfx in demote_prefixes), cname)
    lines = [f'const char *yos_name_{name}(int v)', '{']
    seen: set[int] = set()
    if pairs:
        lines.append('    switch (v) {')
        for cname, gv, _hv in sorted(pairs, key=_sort_key):
            if gv is None or gv in seen:
                continue
            seen.add(gv)
            lines.append(f'    case {gv}: return "{cname}";')
        lines.append('    default:  return (const char *)0;')
        lines.append('    }')
    else:
        lines.append('    (void)v;')
        lines.append('    return (const char *)0;')
    lines.append('}')
    return '\n'.join(lines)


def _emittable_groups(groups: dict) -> list[str]:
    """The 'misc' group is a junk drawer of unrelated namespaces (IGMP
    flags + ELF constants + sysctl numbers + …) that collide on
    integer values without any per-syscall context. Don't emit a
    switch for it; the runtime can't usefully remap a flat 'misc'
    table. Anything truly important should get its own prefix in
    PREFIX_GROUPS."""
    return sorted(g for g in groups if g != 'misc')


def emit_remap_h(groups: dict) -> str:
    out = [_HEADER_PROLOGUE,
           '#ifndef YOS_REMAP_H',
           '#define YOS_REMAP_H',
           '',
           '#ifdef __cplusplus',
           'extern "C" {',
           '#endif',
           '']
    for g in _emittable_groups(groups):
        out.append(f'int yos_remap_{g}_g2h(int v);')
        out.append(f'int yos_remap_{g}_h2g(int v);')
        out.append(f'const char *yos_name_{g}(int v);')
    out += ['',
            '#ifdef __cplusplus',
            '}',
            '#endif',
            '#endif /* YOS_REMAP_H */',
            '']
    return '\n'.join(out)


def emit_remap_c(groups: dict) -> tuple[str, list[str]]:
    """Returns (c_code, all_collision_notes)."""
    out = [_HEADER_PROLOGUE,
           '#include "yos_remap.h"',
           '']
    all_notes: list[str] = []
    for g in _emittable_groups(groups):
        pairs = groups[g]
        out.append(f'/* === {g}: {len(pairs)} entries === */')
        c, notes = _emit_remap_function(g, pairs, 'g2h')
        out.append(c); all_notes.extend(notes); out.append('')
        c, notes = _emit_remap_function(g, pairs, 'h2g')
        out.append(c); all_notes.extend(notes); out.append('')
        out.append(_emit_name_function(g, pairs)); out.append('')
    return '\n'.join(out), all_notes


# ─── Hooks-todo skeleton ─────────────────────────────────────────────

def emit_hooks_todo(analyse: dict) -> str:
    """Produce a YAML skeleton listing every needs_policy function.

    Humans curate this by adding a `strategy:` line per entry. The
    next-stage code generator will read it and emit the chosen
    translator. Until curated, entries default to `strategy: stub`
    which yields -ENOSYS at runtime.
    """
    out = [
        '# Auto-generated by build-tools/api-generate/generate.py.',
        '# This file is the human-curation surface for functions whose',
        '# guest/host signatures differ in ways the auto-classifier',
        "# couldn't bridge mechanically. Pick a `strategy:` for each:",
        '#',
        "#   stub          return -ENOSYS at runtime (default)",
        '#   reject_arity  signature divergence is intentional; reject',
        '#   manual:<id>   point at a hand-written translator function',
        '#                 (the runtime symbol yos_<id>_translate)',
        '#   passthrough_unsafe   call host function unchanged anyway',
        '#                       (only when you know the divergence',
        "#                       won't matter at the call site)",
        '',
        'functions:',
    ]
    for name in sorted(analyse.get('needs_policy', {}).keys()):
        problems = analyse['needs_policy'][name]
        # Compact, single-line summary of what differs per arg.
        verbs = []
        for p in problems:
            d = p.get('delta') or {}
            verbs.append(f'{p.get("arg","?")}={d.get("op","?")}')
        out.append(f'  {name}:')
        out.append(f'    strategy: stub          # diffs: {", ".join(verbs)}')
    return '\n'.join(out) + '\n'


# ─── Stats ───────────────────────────────────────────────────────────

def emit_stats(analyse: dict, groups: dict) -> str:
    s = analyse.get('summary', {})
    lines = [
        'yos api-generate stats',
        '======================',
        '',
        f"compatible (passthrough-eligible): {s.get('compatible', 0)}",
        f"mechanical (auto-bridgeable):      {s.get('mechanical', 0)}",
        f"needs_policy (human-curated):      {s.get('needs_policy', 0)}",
        f"unsupported (extractor bugs):      {s.get('unsupported', 0)}",
        f"variadic_skipped:                  {s.get('variadic_skipped', 0)}",
        f"guest_only:                        {s.get('guest_only', 0)}",
        f"host_only:                         {s.get('host_only', 0)}",
        '',
        'constants_remap groups:',
    ]
    for g in sorted(groups):
        lines.append(f"  {g:12s}  {len(groups[g])} entries")
    lines.append(f"  TOTAL         {sum(len(v) for v in groups.values())}")
    return '\n'.join(lines) + '\n'


# ─── CLI ─────────────────────────────────────────────────────────────

def main() -> int:
    p = argparse.ArgumentParser(description='Generate yos remap code from analyse-report.yaml')
    p.add_argument('--analyse', required=True, type=Path,
                   help='analyse-report.yaml')
    p.add_argument('--out-dir', required=True, type=Path,
                   help='output directory for yos_remap.{h,c}, hooks_todo.yaml, stats.txt')
    args = p.parse_args()

    with args.analyse.open() as f:
        analyse = yaml.safe_load(f)

    remap  = analyse.get('constants_remap', {}) or {}
    groups = _split_groups(remap)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / 'yos_remap.h').write_text(emit_remap_h(groups))
    remap_c, collisions = emit_remap_c(groups)
    (args.out_dir / 'yos_remap.c').write_text(remap_c)
    (args.out_dir / 'hooks_todo.yaml').write_text(emit_hooks_todo(analyse))
    stats_text = emit_stats(analyse, groups)
    if collisions:
        stats_text += '\nremap collisions (first-claim-wins; runtime needs context):\n'
        for n in collisions:
            stats_text += f'  - {n}\n'
    (args.out_dir / 'stats.txt').write_text(stats_text)

    print(f'[api-generate] wrote yos_remap.h, yos_remap.c, hooks_todo.yaml, stats.txt to {args.out_dir}',
          file=sys.stderr)
    print(f'              constants_remap: {sum(len(v) for v in groups.values())} '
          f'entries across {len(groups)} groups', file=sys.stderr)
    print(f'              hooks_todo: {len(analyse.get("needs_policy") or {})} '
          f'functions awaiting curation', file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
