#!/usr/bin/env bash
# Build the Phase 0 browser-convergence host artifact (epic #33, issue #34).
#
#   yos-host-phase0.mjs (+ .wasm) — the wasm3 interpreter compiled to a
#   browser-targeted wasm module with Emscripten, embedding a trivial guest
#   wasm it runs to prove "wasm3-in-wasm" works with zero JS libc.
#
# Three steps:
#   1. compile the trivial guest to wasm32 (own memory, no imports)
#   2. embed those bytes as a C array header (no MEMFS / no JS FS shim)
#   3. emcc-compile phase0_host.c + the vendored wasm3 sources
#
# Toolchain: system `clang` (wasm32 cross) + `emcc` (Emscripten), both on
# PATH via the nix dev profile. Override with YOS_WASM_CLANG / EMCC.
set -euo pipefail
cd "$(dirname "$0")"

# host/ is src/yos/platform/web/host — the repo root is five levels up.
REPO_ROOT="$(cd ../../../../.. && pwd)"
WASM3_SRC="$REPO_ROOT/src/wasm3/source"

CC=${YOS_WASM_CLANG:-clang}
EMCC=${EMCC:-emcc}
PYTHON=${PYTHON:-python3}

# ── 1. Trivial guest → wasm32 ──────────────────────────────────────────
# Stand-alone module: it DEFINES its own linear memory (no --import-memory)
# so wasm3 can instantiate it, and exports a single function `compute`.
"$CC" -target wasm32-unknown-unknown -nostdlib -O2 \
	-Wl,--no-entry -Wl,--export=compute \
	-o smoke_guest.wasm smoke_guest.c
echo "built smoke_guest.wasm ($(wc -c <smoke_guest.wasm) bytes)"

# ── 2. Embed the guest bytes as a C array ──────────────────────────────
# Embedding (vs emcc --embed-file) keeps the path pure C → wasm3 and avoids
# pulling in Emscripten MEMFS + a JS fopen/read filesystem shim.
"$PYTHON" - <<'PY'
data = open("smoke_guest.wasm", "rb").read()
with open("smoke_guest_wasm.h", "w") as out:
    out.write("/* generated by build-phase0.sh — do not edit, not tracked */\n")
    out.write("static const unsigned char smoke_guest_wasm[] = {\n")
    for i in range(0, len(data), 12):
        out.write("  " + ",".join(str(b) for b in data[i:i + 12]) + ",\n")
    out.write("};\n")
    out.write("static const unsigned int smoke_guest_wasm_len = %d;\n" % len(data))
PY
echo "generated smoke_guest_wasm.h"

# ── 3. Emscripten host = wasm3 interpreter + phase0_host.c ──────────────
# Compile flags mirror src/wasm3/meson.build. Optimization is load-bearing:
# wasm3's opcode dispatch only turns into sibling calls at -O2/-O3; at -O0 it
# grows the stack per opcode. -O2 (not -O3) is used because the nix-provided
# emscripten frontend passes an -O3-only binaryen flag (--no-stack-ir) that
# its pinned wasm-opt rejects; -O2 gives the same sibling-call dispatch and
# links cleanly.
WASM3_SOURCES=(
	"$WASM3_SRC/m3_api_libc.c"
	"$WASM3_SRC/m3_atomic.c"
	"$WASM3_SRC/m3_bind.c"
	"$WASM3_SRC/m3_code.c"
	"$WASM3_SRC/m3_compile.c"
	"$WASM3_SRC/m3_core.c"
	"$WASM3_SRC/m3_emit.c"
	"$WASM3_SRC/m3_env.c"
	"$WASM3_SRC/m3_exec.c"
	"$WASM3_SRC/m3_function.c"
	"$WASM3_SRC/m3_info.c"
	"$WASM3_SRC/m3_module.c"
	"$WASM3_SRC/m3_optimize.c"
	"$WASM3_SRC/m3_parse.c"
)

# Link flags: MODULARIZE + EXPORT_ES6 give a default-export factory the node
# harness awaits; overriding print/printErr in the factory arg captures the
# host's stdout. No -pthread — single-threaded musl serves wasm3's mmap
# allocator + registry mutex fine, and pthreads would drag in Workers/COOP.
#
# EXIT_RUNTIME stays OFF (the default): with it on, Emscripten calls
# process.exit() the moment main() returns, killing the node harness before
# it can inspect the captured output. Left off, main() returns, the runtime
# is kept alive, the factory promise resolves, and the harness owns the
# verdict. The host's explicit fflush(stdout) already delivers the line to
# the print hook, so nothing is lost.
"$EMCC" -O2 \
	-I "$WASM3_SRC" -I . \
	-Dd_m3RecordBacktraces=1 -D_GNU_SOURCE -fno-strict-aliasing \
	-Wno-unused-parameter -Wno-unused-variable -Wno-implicit-fallthrough \
	-sMODULARIZE=1 -sEXPORT_ES6=1 -sENVIRONMENT=web,node \
	-sALLOW_MEMORY_GROWTH=1 -sASSERTIONS=1 \
	phase0_host.c phase0_yperf_stub.c "${WASM3_SOURCES[@]}" \
	-o yos-host-phase0.mjs
echo "built yos-host-phase0.mjs ($(wc -c <yos-host-phase0.mjs) bytes) + yos-host-phase0.wasm ($(wc -c <yos-host-phase0.wasm) bytes)"
