#!/usr/bin/env bash
# Build the Phase 1b browser-convergence host (epic #33, issue #36).
#
#   yos-host-phase1b.mjs (+ .wasm) — the REAL generated yos bridge + the yos
#   impl/vfs source trees + wasm3, compiled to a browser wasm module with
#   Emscripten. A guest's env.* libc calls get FreeBSD-shaped behaviour from
#   the same C code desktop runs; Emscripten musl/MEMFS is the substrate below.
#
# Toolchain rules as in build-phase0.sh (guest via system clang; host via nix
# emscripten at -O2). Overrides: YOS_WASM_CLANG, EMCC, PYTHON.
#
# The generated bridge is large (~1.9 MB) so objects are cached in obj/ and
# only recompiled when their source is newer — the first build is slow, reruns
# are fast.
set -euo pipefail
cd "$(dirname "$0")"

REPO_ROOT="$(cd ../../../../.. && pwd)"
WASM3_SRC="$REPO_ROOT/src/wasm3/source"
YOS_SRC="$REPO_ROOT/src/yos"
# Native build dir holding the generated bridge (from `make codegen`). Defaults
# to build-linux; override with YOS_BUILD for darwin/freebsd (build-darwin, …).
YOS_BUILD=${YOS_BUILD:-build-linux}
CODEGEN="$REPO_ROOT/$YOS_BUILD/src/yos/codegen"   # generated bridge/remap/struct_convert

CC=${YOS_WASM_CLANG:-clang}
EMCC=${EMCC:-emcc}
PYTHON=${PYTHON:-python3}

if [ ! -f "$CODEGEN/yos_bridge.c" ]; then
	echo "error: generated bridge not found at $CODEGEN/yos_bridge.c" >&2
	echo "       run the desktop codegen first ('make codegen'), or set YOS_BUILD." >&2
	exit 1
fi

OBJ=obj
mkdir -p "$OBJ"

# ── 1. Guest (echo + cat via env.* imports) → wasm32 ───────────────────
"$CC" -target wasm32-unknown-unknown -nostdlib -O2 \
	-Wl,--no-entry -Wl,--export=_start \
	-o phase1b_guest.wasm phase1b_guest.c
echo "built phase1b_guest.wasm ($(wc -c <phase1b_guest.wasm) bytes)"

# ── 2. Embed the guest bytes ───────────────────────────────────────────
YOS_EMBED_IN=phase1b_guest.wasm YOS_EMBED_OUT=phase1b_guest_wasm.h \
YOS_EMBED_SYM=phase1b_guest_wasm "$PYTHON" - <<'PY'
import os
data = open(os.environ["YOS_EMBED_IN"], "rb").read()
sym = os.environ["YOS_EMBED_SYM"]
with open(os.environ["YOS_EMBED_OUT"], "w") as out:
    out.write("/* generated by build-phase1b.sh — do not edit, not tracked */\n")
    out.write("static const unsigned char %s[] = {\n" % sym)
    for i in range(0, len(data), 12):
        out.write("  " + ",".join(str(b) for b in data[i:i + 12]) + ",\n")
    out.write("};\n")
    out.write("static const unsigned int %s_len = %d;\n" % (sym, len(data)))
PY
echo "generated phase1b_guest_wasm.h"

# ── 3. Compile yos C (generated bridge + impl + vfs + wasm3) → objects ──
INC=(-I "$YOS_SRC" -I "$REPO_ROOT/src" -I "$REPO_ROOT/include"
     -I "$YOS_SRC/generated" -I "$YOS_SRC/vfs" -I "$YOS_SRC/platform/posix"
     -I "$WASM3_SRC" -I "$CODEGEN" -I .)
CFLAGS=(-O2 "${INC[@]}" -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE
        -Wno-implicit-function-declaration -Wno-error=implicit-function-declaration
        -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function
        -Wno-implicit-fallthrough -ferror-limit=0)

# impl/io/file.c (the FILE* stdio table) is intentionally OMITTED from this
# slice. The generated bridge emits its own default Tier-1 impls for the six
# wide-char stdio functions file.c also defines (yos_getwc/putwc/fgetwc/...),
# and wasm LLD has no --allow-multiple-definition, so the two collide. The
# echo/cat slice uses only the raw-fd path (open/read/write/close in io.c), not
# FILE* stdio, so dropping file.c removes the clash with no loss of coverage;
# the bridge's defaults stand in for the FILE* surface, unused here. Re-adding
# file.c properly is a codegen concern (the bridge should not emit defaults for
# hand-written functions) deferred to a later pass.
SOURCES=(
	"$YOS_SRC/impl/io/io.c"          "$YOS_SRC/impl/io/dir.c"
	"$YOS_SRC/impl/io/fifo.c"
	"$YOS_SRC/impl/io/pty.c"         "$YOS_SRC/impl/io/cv_stat.c"
	"$YOS_SRC/impl/mem/mem.c"        "$YOS_SRC/impl/mem/alloc.c"
	"$YOS_SRC/impl/libc/posix.c"     "$YOS_SRC/impl/libc/printf.c"
	"$YOS_SRC/impl/libc/scanf.c"     "$YOS_SRC/impl/libc/env.c"
	"$YOS_SRC/impl/libc/getopt.c"    "$YOS_SRC/impl/libc/tz.c"
	"$YOS_SRC/impl/libc/libc_globals_link.c" "$YOS_SRC/impl/libc/aliases.c"
	"$YOS_SRC/impl/libc/callback.c"  "$YOS_SRC/impl/libc/cv_trace.c"
	"$YOS_SRC/impl/libc/f128.c"      "$YOS_SRC/impl/libc/i128.c"
	"$YOS_SRC/impl/libc/freebsd_userland.c" "$YOS_SRC/impl/libc/fmtcheck_freebsd.c"
	"$YOS_SRC/impl/libc/kqueue.c"    "$YOS_SRC/impl/libc/mbwc.c"
	"$YOS_SRC/impl/libc/pwd.c"       "$YOS_SRC/impl/libc/random.c"
	"$YOS_SRC/impl/libc/regex.c"     "$YOS_SRC/impl/libc/strto.c"
	"$YOS_SRC/impl/libc/sysctl.c"    "$YOS_SRC/impl/libc/syslog_extras.c"
	"$YOS_SRC/impl/proc/proc.c"      "$YOS_SRC/impl/proc/pthread.c"
	"$YOS_SRC/impl/proc/sig.c"       "$YOS_SRC/impl/proc/signal.c"
	"$YOS_SRC/vfs/file.c"            "$YOS_SRC/vfs/mount.c"
	"$YOS_SRC/vfs/procfs.c"
	"$YOS_SRC/ytrace/ytrace.c"       "$YOS_SRC/yperf/yperf.c"
	"$YOS_SRC/yplatform/time/default.c" "$YOS_SRC/yplatform/thread/default.c"
	"$YOS_SRC/yplatform/term/default.c"
	"$WASM3_SRC/m3_api_libc.c" "$WASM3_SRC/m3_atomic.c" "$WASM3_SRC/m3_bind.c"
	"$WASM3_SRC/m3_code.c" "$WASM3_SRC/m3_compile.c" "$WASM3_SRC/m3_core.c"
	"$WASM3_SRC/m3_emit.c" "$WASM3_SRC/m3_env.c" "$WASM3_SRC/m3_exec.c"
	"$WASM3_SRC/m3_function.c" "$WASM3_SRC/m3_info.c" "$WASM3_SRC/m3_module.c"
	"$WASM3_SRC/m3_optimize.c" "$WASM3_SRC/m3_parse.c"
	"$CODEGEN/yos_bridge.c"          "$CODEGEN/yos_remap.c"
	"$CODEGEN/yos_struct_convert.c"
	"$YOS_SRC/generated/struct_convert.c"
	"phase1b_bridge_support.c"
	"phase1b_host.c"
)

objs=()
compiled=0
for src in "${SOURCES[@]}"; do
	# Unique object name: hash the path into the basename to avoid collisions
	# (several files are named default.c / struct_convert.c).
	tag=$(echo "$src" | sed 's|.*/src/||; s|[/.]|_|g')
	obj="$OBJ/$tag.o"
	objs+=("$obj")
	if [ ! -f "$obj" ] || [ "$src" -nt "$obj" ]; then
		"$EMCC" -c "${CFLAGS[@]}" "$src" -o "$obj"
		compiled=$((compiled + 1))
	fi
done
echo "compiled $compiled/${#SOURCES[@]} objects (rest cached in $OBJ/)"

# ── 4. Link the host wasm ──────────────────────────────────────────────
# -sERROR_ON_UNDEFINED_SYMBOLS=0: the generated bridge references the FULL
# impl surface (fork/pthread/etc.); anything not compiled here becomes an inert
# import stub the echo/cat guest never calls.
# --embed-file: the cat test file, placed in the MEMFS substrate under yos VFS.
"$EMCC" -O2 "${objs[@]}" \
	-sMODULARIZE=1 -sEXPORT_ES6=1 -sENVIRONMENT=web,node \
	-sALLOW_MEMORY_GROWTH=1 -sASSERTIONS=1 -sERROR_ON_UNDEFINED_SYMBOLS=0 \
	--embed-file phase1b_data.txt@/phase1b.txt \
	-o yos-host-phase1b.mjs
echo "built yos-host-phase1b.mjs ($(wc -c <yos-host-phase1b.mjs) bytes) + yos-host-phase1b.wasm ($(wc -c <yos-host-phase1b.wasm) bytes)"
