#!/usr/bin/env bash
# Build the Phase 1a browser-convergence host (epic #33, issue #35).
#
#   yos-host-phase1a.mjs (+ .wasm) — wasm3 compiled to a browser wasm module,
#   serving a guest's env.write / env.getpid / env.exit imports through C
#   bridge wrappers (pointer translation ctx->memory + offset), not JS.
#
# Same three steps and toolchain rules as build-phase0.sh (see that script's
# header and host/README.md): guest via system clang, host via nix emscripten
# at -O2. Overrides: YOS_WASM_CLANG, EMCC, PYTHON.
set -euo pipefail
cd "$(dirname "$0")"

REPO_ROOT="$(cd ../../../../.. && pwd)"
WASM3_SRC="$REPO_ROOT/src/wasm3/source"

CC=${YOS_WASM_CLANG:-clang}
EMCC=${EMCC:-emcc}
PYTHON=${PYTHON:-python3}

# ── 1. Guest with real env.* libc imports → wasm32 ─────────────────────
"$CC" -target wasm32-unknown-unknown -nostdlib -O2 \
	-Wl,--no-entry -Wl,--export=_start \
	-o bridge_guest.wasm bridge_guest.c
echo "built bridge_guest.wasm ($(wc -c <bridge_guest.wasm) bytes)"

# ── 2. Embed the guest bytes as a C array ──────────────────────────────
YOS_EMBED_IN=bridge_guest.wasm YOS_EMBED_OUT=bridge_guest_wasm.h \
YOS_EMBED_SYM=bridge_guest_wasm "$PYTHON" - <<'PY'
import os
src = os.environ["YOS_EMBED_IN"]
dst = os.environ["YOS_EMBED_OUT"]
sym = os.environ["YOS_EMBED_SYM"]
data = open(src, "rb").read()
with open(dst, "w") as out:
    out.write("/* generated by build-phase1a.sh — do not edit, not tracked */\n")
    out.write("static const unsigned char %s[] = {\n" % sym)
    for i in range(0, len(data), 12):
        out.write("  " + ",".join(str(b) for b in data[i:i + 12]) + ",\n")
    out.write("};\n")
    out.write("static const unsigned int %s_len = %d;\n" % (sym, len(data)))
PY
echo "generated bridge_guest_wasm.h"

# ── 3. Emscripten host = wasm3 + phase1a_host.c ────────────────────────
# -O2 (not -O3): the packaged emscripten's -O3 binaryen flag --no-stack-ir is
# rejected by its wasm-opt; -O2 gives the same wasm3 sibling-call dispatch.
WASM3_SOURCES=(
	"$WASM3_SRC/m3_api_libc.c" "$WASM3_SRC/m3_atomic.c" "$WASM3_SRC/m3_bind.c"
	"$WASM3_SRC/m3_code.c" "$WASM3_SRC/m3_compile.c" "$WASM3_SRC/m3_core.c"
	"$WASM3_SRC/m3_emit.c" "$WASM3_SRC/m3_env.c" "$WASM3_SRC/m3_exec.c"
	"$WASM3_SRC/m3_function.c" "$WASM3_SRC/m3_info.c" "$WASM3_SRC/m3_module.c"
	"$WASM3_SRC/m3_optimize.c" "$WASM3_SRC/m3_parse.c"
)
"$EMCC" -O2 \
	-I "$WASM3_SRC" -I . \
	-Dd_m3RecordBacktraces=1 -D_GNU_SOURCE -fno-strict-aliasing \
	-Wno-unused-parameter -Wno-unused-variable -Wno-implicit-fallthrough \
	-sMODULARIZE=1 -sEXPORT_ES6=1 -sENVIRONMENT=web,node \
	-sALLOW_MEMORY_GROWTH=1 -sASSERTIONS=1 \
	phase1a_host.c phase0_yperf_stub.c "${WASM3_SOURCES[@]}" \
	-o yos-host-phase1a.mjs
echo "built yos-host-phase1a.mjs ($(wc -c <yos-host-phase1a.mjs) bytes) + yos-host-phase1a.wasm ($(wc -c <yos-host-phase1a.wasm) bytes)"
