/* Tier 2 — sidecar wasm runtime hosting FreeBSD libc fns.
 *
 * yos's build produces `libc-pure.wasm` (see build-tools/freebsd-libc/)
 * containing pure-userspace libc functions sourced from FreeBSD libc
 * source. yos loads this sidecar into a SECONDARY wasm3 instance at
 * startup. When the GUEST imports a Tier-2 libc function, the bridge
 * dispatches into the sidecar via the helpers below.
 *
 * The sidecar runtime is shared across guest forks — Tier 2 functions
 * are pure (no per-process state).
 */
#ifndef YOS_IMPL_TIER2_H
#define YOS_IMPL_TIER2_H

#include <stdint.h>

struct M3Runtime;
typedef struct M3Runtime *IM3Runtime;
struct M3Function;
typedef struct M3Function *IM3Function;

/* Load libc-pure.wasm into a fresh wasm3 instance. Returns 0 on
 * success, -1 on any failure (file not found, parse error, link
 * error). On failure yos still runs — Tier 2 fns will resolve to
 * -ENOSYS at call time. */
int yos_tier2_init(const char *libc_pure_path);

/* Look up an exported function in the sidecar by name. Returns NULL
 * if Tier 2 isn't initialised or the function isn't present. */
IM3Function yos_tier2_find(const char *name);

/* Bridges generated by bridge.py for `from_freebsd_src` functions
 * call this helper once at first use to cache the resolved
 * IM3Function. */
IM3Function yos_tier2_resolve_once(IM3Function *cache, const char *name);

#endif /* YOS_IMPL_TIER2_H */
